### PR TITLE
Add support for spread attributes

### PR DESCRIPTION
**Pull request by bryce-gibson**
This is only very lightly tested (will test more in coming days, but didn't want to forget to create a PR), but I _think_ it adds support for spread operators, eg:

```
<div {...props} name="something"></div>
```

to

```
attrs: Object.assign({}, props, {
  "name": "something
}),
```

ish :-)

Just pilfered from coffee-react-transform, with `React.__spread` changed to `Object.assign`.

No problem if you don't want it or any such :-)

ps, for contrast, without this I get:

```
attrs: {
  "props": props,
  "name": "something
},
```

### CODE REVIEW

**Comment by sixmen** [comment]
Please add also test cases for this.
(You can take them from test/output-testcases.txt of coffee-react-transform)

**Comment by bryce-gibson** [comment]
Ooh, great plan :-)

Thanks for the feedback, will do :-)

Might take a few days, but will get them done :-)

**Comment by bryce-gibson** [comment]
Tests added :-)

I also added an npm `test` property as well to allow running `npm test`, hopefully that's alright? :-)

I had to fudge around with the whitespace when porting the tests, but I can't see how that would cause any issues? Just wanted to mention it in case it's important in a way that I don't know of :-s

**Comment by sixmen** [comment]
It seems all right. Thank you.

**Comment by bryce-gibson** [comment]
No problem, thank you more importantly :-)

**Pull request merged**
